import React from 'react'

function Ido2020() {
  return (
    <p>We facilitate and record donations in kind or in material goods, made on a peer-to-peer basis, on the Utopiamaker social network.<br/><br/>
    The “Change le monde” association, in charge of managing this network, regulates, documents and transparently shares these exchanges of non-commercial services between people.<br/><br/>
    
    The IDO2020 application currently allows you to use these peer-to-peer exchange instruments in your own organization, under a white label.<br/><br/>    
    The IDO2020 standard regulates this application plan and will be the heart of this decentralized project that unites us: transparency in front of all the actors, from the donor to the beneficiary, the recognition of the work and the raison d’être of each one of the volunteers. , the leadership of the beneficiaries in the projects that concern them, the unconditional sharing of knowledge and the experience acquired. Placing the human being at the center of socially oriented organizations.<br/><br/>
    
    We call on all people involved in socially oriented organizations to appropriate and develop these instruments in order to fully apply the fundamental values ​​that characterize their own organization.<br/><br/>
    
    Our goal is to give our organizations the tools to apply the core values ​​they uphold:<br/><br/>
    
    Transparency in front of all the actors, from the donor to the beneficiary.<br/><br/>
    
    Recognition of the work and the reason for being of each of the actors.<br/><br/>
    
    Leadership of the users in the projects that concern them.<br/><br/>
    
    Unconditionally share the knowledge and experience acquired.<br/><br/>
    
    Our users will be all people related to socially oriented organizations: volunteers, beneficiaries, leaders, employees, donors, etc., whether on a daily or occasional basis. Social organizations: associations according to Law 1901, NGOs, ESS, Social Spaces, Start-ups with social purposes, etc.<br/><br/>
    
    We invite our users to a collaborative and evolutionary use of our application: that they can appropriate our tool and develop its concrete possibilities through an active peer-to-peer collaboration.<br/><br/>
    
    The main objective is to facilitate and develop the effective implementation of the fundamental values ​​that characterize social organizations.<br/><br/>
    
    Interaction for the De-normalization of Social Organizations<br/><br/>
    
    Interaction: placing the individual as a creator of wealth in their interactions at the center of the organization. Change the axis of organizations through dual governance and cellular functioning.<br/><br/>
    De-normalization: the term “de-normalization” comes from computer language and means changing the behavior of a database: mainly, going from an individual reference (a person with their information) to a relational reference (the interactions that are created around that person). The data corresponds to this network operation made up of all the interactions generated by people. Today they constitute our greatest resource and the main source of wealth creation in the world.<br/><br/>
    Social Organizations: This project is primarily intended for socially oriented organizations.<br/><br/>
    
    In 2020, the project was created with the aim of disseminating and raising awareness about an operating model centered on the individual, which allows the effective application of fundamental values ​​in social organizations. This project is carried out through the Utopiamaker platform, managed by the “Change le monde” association. The IDO2020 application is used in this project, in order to regulate and document material and non-monetary donations made between peers.<br/><br/>
    
    The project is limited to the decade of the 20s, specifically until February 2, 2030, since its purpose is to free the individual from the organization and not perpetuate its existence beyond its mission. The goal is to generate awareness around this operating model, so that people can adopt and use it naturally and regularly, until the tool becomes useless or absurd.<br/><br/>
    
    The self-managed collective seeks to place the human being at the center of common organizations and projects, and considers that each common action is conditioned by the respect, autonomy, and responsibility of each individual involved. Their goal is to build collective autonomy through mass membership in which each is involved in recruiting new members, using a computer network to allow each to sponsor at least two people, with the goal of reaching one million of members and a budget of at least three million euros.<br/><br/>
    
    The objective of the collective is to experiment with collective and constructive governance for issues that unite us beyond tribal controversies and opinions. The stages of the project include the constitution of own funds, digital participatory democracy, collective management of the common good and the guarantee of individual sovereignty of all the people involved in collective development.<br/><br/>
    
    The regulation of donations and the management of social projects is carried out through the IDO2020 application, which is governed by the rules of transparency towards all actors, the recognition of the work and the purpose of each volunteer, the leadership of the beneficiaries for the projects that concern them, the unconditional exchange of knowledge and experience and the placement of the human being at the center of social organizations.<br/><br/>
    
    Each member is active from the beginning in the sponsorship of two friends and in their financial contribution. The management of social projects is carried out in a similar way, allowing each one to have the freedom of their voice and action. Every penny is personally attributed to the projects and actions that affect each individual.<br/><br/>
    
    The regulation will be carried out through the algorithm programmed according to the following IDO2020** standards: Transparency with respect to all the actors, from the donor to the beneficiary, the recognition of the work and the purpose of each one of the volunteers, the leadership of the beneficiaries for the projects that concern them, the unconditional exchange of knowledge and experience acquired. Placing the human being at the center of socially oriented organizations.<br/><br/>
    
    *star wars<br/><br/>
    ** The IDO2020 instruments and standards can be used in a white label by all social organizations that wish to do so.<br/><br/>
    </p>
  )
}

export default Ido2020